# Generated by Django 3.0.7 on 2020-06-21 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullid', models.TextField(max_length=9)),
                ('real_name', models.TextField(max_length=50)),
                ('tz', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Activity_period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TextField(max_length=100)),
                ('end_time', models.TextField(max_length=100)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Member')),
            ],
        ),
    ]
